#!/bin/bash
CONFIGURATION_PATH="./DefaultDocumentation.json"

MONOGAME_ASEPRITE_ASSEMBLY_NAME="MonoGame.Aseprite"
MONOGAME_ASEPRITE_DIR="../source/${MONOGAME_ASEPRITE_ASSEMBLY_NAME}"
MONOGAME_ASEPRITE_PROJ_PATH="${MONOGAME_ASEPRITE_DIR}/${MONOGAME_ASEPRITE_ASSEMBLY_NAME}.csproj"
MONOGAME_ASEPRITE_ASSEMBLY="${MONOGAME_ASEPRITE_DIR}/bin/Debug/net6.0/${MONOGAME_ASEPRITE_ASSEMBLY_NAME}.dll"
MONOGAME_ASEPRITE_XML="${MONOGAME_ASEPRITE_DIR}/bin/Debug/net6.0/${MONOGAME_ASEPRITE_ASSEMBLY_NAME}.xml"
MONOGAME_ASEPRITE_OUTPUT="./${MONOGAME_ASEPRITE_ASSEMBLY_NAME}"

MONOGAME_ASEPRITE_COMMON_ASSEMBLY_NAME="MonoGame.Aseprite.Common"
MONOGAME_ASEPRITE_COMMON_DIR="../source/${MONOGAME_ASEPRITE_COMMON_ASSEMBLY_NAME}"
MONOGAME_ASEPRITE_COMMON_PROJ_PATH="${MONOGAME_ASEPRITE_COMMON_DIR}/${MONOGAME_ASEPRITE_COMMON_ASSEMBLY_NAME}.csproj"
MONOGAME_ASEPRITE_COMMON_ASSEMBLY="${MONOGAME_ASEPRITE_COMMON_DIR}/bin/Debug/net6.0/${MONOGAME_ASEPRITE_COMMON_ASSEMBLY_NAME}.dll"
MONOGAME_ASEPRITE_COMMON_XML="${MONOGAME_ASEPRITE_COMMON_DIR}/bin/Debug/net6.0/${MONOGAME_ASEPRITE_COMMON_ASSEMBLY_NAME}.xml"
MONOGAME_ASEPRITE_COMMON_OUTPUT="./${MONOGAME_ASEPRITE_COMMON_ASSEMBLY_NAME}"

MONOGAME_ASEPRITE_CONTENT_PIPELINE_ASSEMBLY_NAME="MonoGame.Aseprite.Content.Pipeline"
MONOGAME_ASEPRITE_CONTENT_PIPELINE_DIR="../source/${MONOGAME_ASEPRITE_CONTENT_PIPELINE_ASSEMBLY_NAME}"
MONOGAME_ASEPRITE_CONTENT_PIPELINE_PROJ_PATH="${MONOGAME_ASEPRITE_CONTENT_PIPELINE_DIR}/${MONOGAME_ASEPRITE_CONTENT_PIPELINE_ASSEMBLY_NAME}.csproj"
MONOGAME_ASEPRITE_CONTENT_PIPELINE_ASSEMBLY="${MONOGAME_ASEPRITE_CONTENT_PIPELINE_DIR}/bin/Debug/net6.0/${MONOGAME_ASEPRITE_CONTENT_PIPELINE_ASSEMBLY_NAME}.dll"
MONOGAME_ASEPRITE_CONTENT_PIPELINE_XML="${MONOGAME_ASEPRITE_CONTENT_PIPELINE_DIR}/bin/Debug/net6.0/${MONOGAME_ASEPRITE_CONTENT_PIPELINE_ASSEMBLY_NAME}.xml"
MONOGAME_ASEPRITE_CONTENT_PIPELINE_OUTPUT="./${MONOGAME_ASEPRITE_CONTENT_PIPELINE_ASSEMBLY_NAME}"

# Ensure the DefaultDocument plugin is built
dotnet build ../source/DefaultDocumentation.Plugin/DefaultDocumentation.Plugin.csproj

defaultdocumentation --AssemblyFilePath $MONOGAME_ASEPRITE_ASSEMBLY --DocumentationFilePath $MONOGAME_ASEPRITE_XML --ProjectDirectoryPath $MONOGAME_ASEPRITE_PROJ_PATH --OutputDirectoryPath $MONOGAME_ASEPRITE_OUTPUT --ConfigurationFilePath $CONFIGURATION_PATH --AssemblyPageName $MONOGAME_ASEPRITE_ASSEMBLY_NAME

defaultdocumentation --AssemblyFilePath $MONOGAME_ASEPRITE_COMMON_ASSEMBLY --DocumentationFilePath $MONOGAME_ASEPRITE_COMMON_XML --ProjectDirectoryPath $MONOGAME_ASEPRITE_COMMON_PROJ_PATH --OutputDirectoryPath $MONOGAME_ASEPRITE_COMMON_OUTPUT --ConfigurationFilePath $CONFIGURATION_PATH --AssemblyPageName $MONOGAME_ASEPRITE_COMMON_ASSEMBLY_NAME

defaultdocumentation --AssemblyFilePath $MONOGAME_ASEPRITE_CONTENT_PIPELINE_ASSEMBLY --DocumentationFilePath $MONOGAME_ASEPRITE_CONTENT_PIPELINE_XML --ProjectDirectoryPath $MONOGAME_ASEPRITE_CONTENT_PIPELINE_PROJ_PATH --OutputDirectoryPath $MONOGAME_ASEPRITE_CONTENT_PIPELINE_OUTPUT --ConfigurationFilePath $CONFIGURATION_PATH --AssemblyPageName $MONOGAME_ASEPRITE_CONTENT_PIPELINE_ASSEMBLY_NAME
