<Project Sdk="Microsoft.NET.Sdk">

    <!-- Project level compilation properties -->
    <PropertyGroup>
        <TargetFrameworks>net8.0</TargetFrameworks>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <!-- Project level package properties -->
    <PropertyGroup>
        <DefineConstants>$(DefineConstants);KNI</DefineConstants>
        <PackageId>KNI.Aseprite</PackageId>
        <Description>
            KNI.Aseprite is a cross-platform C# library that adds support to KNI projects for
            Aseprite (.asepirte/.ase) files.
        </Description>
    </PropertyGroup>

    <!-- Includes for NuGets -->
    <ItemGroup>
        <None Include="..\..\.images\nuget-icon.png" Pack="true" PackagePath="" />
        <None Include="..\..\README.md" Pack="true" PackagePath="" />
        <None Include="$(OutDir)KNI.Aseprite.xml" Pack="true" PackagePath="lib\net8.0" />
        <None Include="..\..\.artifacts\src\bin\KNI.Aseprite.Content.Pipeline\release\KNI.Aseprite.Content.Pipeline.dll" Pack="true" PackagePath="content" />
    </ItemGroup>

    <!-- NuGet Package References -->
    <ItemGroup>
        <PackageReference Include="AsepriteDotNet" Version="1.9.1" />
    </ItemGroup>

    <!-- Allow Test project to access internals -->
    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>KNI.Aseprite.Tests</_Parameter1>
        </AssemblyAttribute>

        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>KNI.Aseprite.Content.Pipeline</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <!-- Warning Suppressions -->
    <PropertyGroup>
        <!-- Suppress warning about Pipeline dll not being in lib folder for NuGet -->
        <NoWarn>NU5100</NoWarn>
    </PropertyGroup>
</Project>
