/* -----------------------------------------------------------------------------
Copyright 2022 Christopher Whitley

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
----------------------------------------------------------------------------- */
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Content.Pipeline;
using Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler;
using Microsoft.Xna.Framework.Graphics;
using MonoGame.Aseprite.Content.Pipeline.Processors;

namespace MonoGame.Aseprite.Content.Pipeline.Writers;

public sealed class AsepriteImageWriter : ContentTypeWriter<AsepriteImageProcessorResult>
{
    protected override void Write(ContentWriter output, AsepriteImageProcessorResult input)
    {
        //  Mimic the Texture2D content writer
        //  https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework.Content.Pipeline/Serialization/Compiler/Texture2DContentWriter.cs
        output.Write((int)SurfaceFormat.Color);
        output.Write(input.Width);
        output.Write(input.Height);

        //  The native Texture2D content that is generated by the pipeline
        //  can have mipmaps generated. This library does not generate mipmaps
        //  so this just outputs that there is 1
        output.Write(1);
        output.Write(input.Pixels.Length);

        for (int i = 0; i < input.Pixels.Length; i++)
        {
            output.Write(input.Pixels[i]);
        }
    }


    public override string GetRuntimeReader(TargetPlatform targetPlatform)
    {
        //  Use the native Texture2DReader
        //  https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework.Content.Pipeline/Serialization/Compiler/Texture2DContentWriter.cs
        return $"{typeof(ContentTypeReader).Namespace}.Texture2DReader";
    }
}
