name: publish
on:
  push:
    tags:
      - 'release/*'


env: 
  DOTNET_VERSION: '6.0.400'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Output Dir
        shell: bash
        run: |
          pwd
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cake Target Test
        shell: bash
          env: 
            NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
            GITHUB_TOKEN: ${{ github.token }}
        run: |
          dotnet new tool-manifest
          dotnet tool install Cake.Tool
          dotnet tool restore
          dotnet cake --target=Publish